### ISSUE TITLE
中文部分无法显示

### ISSUE THREAD

**Issue by zer0yu** [wh1t3zer/SpringBootVul-GUI#1]
我在 wsl 中的 ubuntu 运行的该程序，中文无法显示。已经安装了中文字体，并且之前的 哥斯拉 工具是正常的。不太清楚是什么情况。

cmd
```
java -Dfile.encoding=UTF-8 -jar SpringBootVul_GUI.ja
```

![image](https://github.com/user-attachments/assets/7d3b66a5-dd44-4e77-84ab-91607724596a)

**Comment by wh1t3zer** [comment]
解决了吗，我改了下字体设置，看看有没有问题

**Comment by ruisika** [comment]
![image](https://github.com/user-attachments/assets/2ae1f818-09d8-488d-bdc3-20a491a000b9)

**Comment by DOGE89757** [comment]
直接下载[SpringBootVul_GUI.zip](https://github.com/wh1t3zer/SpringBootVul-GUI/releases/download/v0.0.5/SpringBootVul_GUI.zip)解压后运行，提示缺少src\main\list.json文件，需要拷贝src目录。
 运行后“漏洞列表中文乱码“，将list.json使用记事本打开后保存为ANSI编码后解决

**Comment by wh1t3zer** [comment]
> ![image](https://private-user-images.githubusercontent.com/87137234/366681008-2ae1f818-09d8-488d-bdc3-20a491a000b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDY5MzEsIm5iZiI6MTcyNjEwNjYzMSwicGF0aCI6Ii84NzEzNzIzNC8zNjY2ODEwMDgtMmFlMWY4MTgtMDlkOC00ODhkLWJkYzMtMjBhNDkxYTAwMGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAyMDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMTIxNjUyOTI0ZjRhYWJhNDQzOWE3YTYyNGY2NDUyZmMwNWVkNGE5MmQ5MjljMTM3MGUzNTBjOWU4MTFhNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FxYnqhPAYCt1k7Fueec1ehFmggYjeTnu5iOB9T1EXmU)

应该fix了，师傅麻烦再看看

**Comment by wh1t3zer** [comment]
> 直接下载[SpringBootVul_GUI.zip](https://github.com/wh1t3zer/SpringBootVul-GUI/releases/download/v0.0.5/SpringBootVul_GUI.zip)解压后运行，提示缺少src\main\list.json文件，需要拷贝src目录。 运行后“漏洞列表中文乱码“，将list.json使用记事本打开后保存为ANSI编码后解决

json刚才不知道啥问题出错了，现在应该可以了，乱码问题也解决，师傅麻烦看看，感谢提醒

**Comment by ruisika** [comment]
我的ok了

**Comment by zer0yu** [comment]
我这里还是不行，X_X，我再配置下字体看看吧，辛苦师傅
