### ISSUE TITLE
没有发现jolokia依赖

### ISSUE THREAD

**Issue by lovechuxin** [wh1t3zer/SpringBootVul-GUI#10]
这个依赖需要自己加吗
<img width="537" alt="image" src="https://github.com/user-attachments/assets/3bec5ced-831f-4dda-b84d-48e3ededfd06">

**Comment by wh1t3zer** [comment]
不是，这里是判断目标服务器上没有这个包，就是大概率不存在这个jolokia相关的漏洞

**Comment by lovechuxin** [comment]
好的明白了感谢大佬
