### ISSUE TITLE
https站点扫描报错

### ISSUE THREAD

**Issue by 419066074** [wh1t3zer/SpringBootVul-GUI#3]
师傅，目前扫描带https的spring站点会出现错误，建议增加忽略ssl证书错误。
<img width="528" alt="image" src="https://github.com/user-attachments/assets/495e0314-2df6-4d7d-b065-42ff42569b63">
<img width="889" alt="image" src="https://github.com/user-attachments/assets/8cbca204-5167-4da2-bee0-cbd280348a21">

**Comment by wh1t3zer** [comment]
> 师傅，目前扫描带https的spring站点会出现错误，建议增加忽略ssl证书错误。 <img alt="image" width="528" src="https://private-user-images.githubusercontent.com/18423034/366695822-495e0314-2df6-4d7d-b065-42ff42569b63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDM5MDAsIm5iZiI6MTcyNjE0MzYwMCwicGF0aCI6Ii8xODQyMzAzNC8zNjY2OTU4MjItNDk1ZTAzMTQtMmRmNi00ZDdkLWIwNjUtNDJmZjQyNTY5YjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDEyMjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViN2M5NzY4Y2RmN2I3MDA3OGVmM2IzZjAxMDUzMGQxOTllNDMxNGM1ZDI0NWEzYzY1ZjNiYjBhODEyNWM2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fVGlzCiCIQ8JUCwD7aiK0RYqgEeAOlvUYAYNj_qvtzs"> <img alt="image" width="889" src="https://private-user-images.githubusercontent.com/18423034/366696238-8cbca204-5167-4da2-bee0-cbd280348a21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDM5MDAsIm5iZiI6MTcyNjE0MzYwMCwicGF0aCI6Ii8xODQyMzAzNC8zNjY2OTYyMzgtOGNiY2EyMDQtNTE2Ny00ZGEyLWJlZTAtY2JkMjgwMzQ4YTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDEyMjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NmRmMWEzMjk2NzA4ODI5OTg5ZTFkY2UyNGE5YjBlZjM0OWE2ZDFlMmVhMjUxMDlmZGRkYTJiYjllYzFmMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pCA7kaN65-XkOo1grt0pbhQ8E-fQm4tEfN2zZ_B1UQw">

感谢提供意见，之前是打算晚点加的，新版本已经加入了，看看尝试下可不可以

**Comment by 419066074** [comment]
高产👍，ssl的问题修复了，然后还有一个问题，当heapdump的大小超过100m会提示429错误，感觉像是文件流太大，没有分割组合直接下载导致。
<img width="466" alt="image" src="https://github.com/user-attachments/assets/196b5640-bf91-4c40-a8b1-82b4f14a6a41">

**Comment by wh1t3zer** [comment]
收到，下个版本加入

**Comment by wh1t3zer** [comment]
> 高产👍，ssl的问题修复了，然后还有一个问题，当heapdump的大小超过100m会提示429错误，感觉像是文件流太大，没有分割组合直接下载导致。 <img alt="image" width="466" src="https://private-user-images.githubusercontent.com/18423034/367124701-196b5640-bf91-4c40-a8b1-82b4f14a6a41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTQ0ODQsIm5iZiI6MTcyNjE5NDE4NCwicGF0aCI6Ii8xODQyMzAzNC8zNjcxMjQ3MDEtMTk2YjU2NDAtYmY5MS00YzQwLWE4YjEtODJiNGYxNGE2YTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAyMjMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NmU3YjFlMjQ0ZDUxNGYyMzEyYzA4YTAxM2Q1YWQ5MDYxOTkwNGEyNjQwNWU3NDhiZGQ1YTU1Mzg5MWU3MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hjWN_6khtRkULZPQERiTLiynO28h563RzckF5IEEuqc">

收到，在下个版本中会加入

**Comment by wh1t3zer** [comment]
> 高产👍，ssl的问题修复了，然后还有一个问题，当heapdump的大小超过100m会提示429错误，感觉像是文件流太大，没有分割组合直接下载导致。 <img alt="image" width="466" src="https://private-user-images.githubusercontent.com/18423034/367124701-196b5640-bf91-4c40-a8b1-82b4f14a6a41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNDk2MTAsIm5iZiI6MTcyNjI0OTMxMCwicGF0aCI6Ii8xODQyMzAzNC8zNjcxMjQ3MDEtMTk2YjU2NDAtYmY5MS00YzQwLWE4YjEtODJiNGYxNGE2YTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE3NDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYmFmOWRmNTZkMGU4YmM1MjdmMmY3NmZhY2M4NDYzNGY5MmVmNGZlNTJjZDIxMzQzMzU5YjlkNzM5ZGMwMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xCB77SeFOhbvVUedZxUiSmThe16SV0YWjsZC1857Ess">

新版本已加入分块下载，并且加了个伪进度条，以后改为进度条
