### ISSUE TITLE
内存马功能bug

### ISSUE THREAD

**Issue by He1za1** [wh1t3zer/SpringBootVul-GUI#9]
![image](https://github.com/user-attachments/assets/7f003474-eabb-4891-82c0-37d7eaee0dcb)

**Comment by wh1t3zer** [comment]
![](https://github.com/user-attachments/assets/d80af451-5b10-4d6d-8078-1f0b25b5e326)
刚才试了下可以，改了一个变量，但是不是这里引起，你再试试latest版
